--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.124.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04/12/2019 10:14:58 SA
-- Server version: 8.0.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS houses;

CREATE DATABASE houses
CHARACTER SET utf8mb4
COLLATE utf8mb4_vietnamese_ci;

--
-- Set default database
--
USE houses;

--
-- Create table `houses1`
--
CREATE TABLE houses1 (
  house_id bigint(20) NOT NULL AUTO_INCREMENT,
  address varchar(255) DEFAULT NULL,
  bedroom int(11) NOT NULL,
  direction varchar(255) DEFAULT NULL,
  floor int(11) NOT NULL,
  house_level varchar(255) DEFAULT NULL,
  house_name varchar(255) DEFAULT NULL,
  image_url varchar(255) DEFAULT NULL,
  restroom int(11) NOT NULL,
  user_id varchar(255) DEFAULT NULL,
  PRIMARY KEY (house_id)
)
ENGINE = MYISAM,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 82,
CHARACTER SET utf8mb4,
CHECKSUM = 0,
COLLATE utf8mb4_vietnamese_ci;

--
-- Create table `houses`
--
CREATE TABLE houses (
  house_id int(11) NOT NULL AUTO_INCREMENT,
  user_id varchar(255) DEFAULT NULL,
  post_id int(11) DEFAULT NULL,
  house_level varchar(255) DEFAULT NULL,
  floor int(11) DEFAULT NULL,
  restroom int(11) DEFAULT NULL,
  bedroom int(11) DEFAULT NULL,
  create_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (house_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 18,
AVG_ROW_LENGTH = 1024,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci;

-- 
-- Dumping data for table houses1
--
INSERT INTO houses1 VALUES
(1, '123A Nguyễn Văn Linh ', 2, 'Tây Nam', 1, 'nha cap 4', 'haha', 'google.com.vn', 1, '1'),
(2, 'Chung cư An Hòa', 2, 'Đông Bắc', 1, '4', 'none', 'check-in', 1, '1'),
(3, '27 đường 3/2', 2, 'Đông Bắc', 2, '4', 'none', 'check-in', 2, '1'),
(4, '321 Trần Hưng Đạo', 1, 'Đông Bắc', 0, '4', 'none', '', 2, '1'),
(5, '132 Võ Văn Kiệt', 1, 'Đông Nam', 1, '4', 'none', 'agent-01.jpg', 2, '1'),
(6, '34 đường 30/2', 2, 'Đông Nam', 2, '1', 'none', 'bds2.jpg', 1, '1');

-- 
-- Dumping data for table houses
--
INSERT INTO houses VALUES
(1, '1', 2, 'Nha cap 4', 3, 1, 2, '2019-11-11 08:54:41', '2019-11-11 08:54:41'),
(2, NULL, 3, '4', 2, 2, 2, '2019-11-16 02:53:59', '2019-11-16 02:53:59'),
(3, NULL, 3, '4', 2, 2, 2, '2019-11-16 03:13:40', '2019-11-16 03:13:40'),
(4, NULL, 3, '4', 2, 2, 2, '2019-11-16 07:15:38', '2019-11-16 07:15:38'),
(5, NULL, 3, '4', 2, 2, 2, '2019-11-16 07:17:17', '2019-11-16 07:17:17'),
(6, '1', 3, 'Nha cap 4', 3, 1, 2, '2019-11-16 12:29:06', '2019-11-16 12:29:06'),
(7, NULL, 4, NULL, 1, 1, 1, '2019-11-16 12:39:21', '2019-11-16 12:39:21'),
(8, NULL, 4, NULL, 1, 1, 1, '2019-11-16 12:49:16', '2019-11-16 12:49:16'),
(9, '1', 4, '2', 1, 1, 1, '2019-11-16 12:56:16', '2019-11-16 12:56:16'),
(10, '1', 5, '1', 3, 1, 1, '2019-11-16 14:02:00', '2019-11-16 14:02:00'),
(11, '1', 6, '1', 3, 1, 1, '2019-11-16 14:04:27', '2019-11-16 14:04:27'),
(12, '1', 7, '1', 3, 1, 1, '2019-11-16 14:59:10', '2019-11-16 14:59:10'),
(13, '1', 8, '4', 2, 2, 2, '2019-11-16 15:10:02', '2019-11-16 15:10:02'),
(14, '1', 9, '1', 1, 1, 1, '2019-11-17 01:16:44', '2019-11-17 01:16:44'),
(15, '1', 10, '4', 1, 2, 1, '2019-11-17 07:44:33', '2019-11-17 07:44:33'),
(16, '1', 11, '1', 2, 2, 1, '2019-11-28 16:44:13', '2019-11-28 16:44:13'),
(17, '1', 11, '1', 2, 2, 1, '2019-11-28 17:00:48', '2019-11-28 17:00:48');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;