--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.124.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04/12/2019 10:15:26 SA
-- Server version: 8.0.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS lands;

CREATE DATABASE lands
CHARACTER SET utf8mb4
COLLATE utf8mb4_vietnamese_ci;

--
-- Set default database
--
USE lands;

--
-- Create table `lands1`
--
CREATE TABLE lands1 (
  land_id bigint(20) NOT NULL AUTO_INCREMENT,
  address varchar(255) DEFAULT NULL,
  direction varchar(255) DEFAULT NULL,
  facade_area varchar(255) DEFAULT NULL,
  image_url varchar(255) DEFAULT NULL,
  user_id varchar(255) DEFAULT NULL,
  PRIMARY KEY (land_id)
)
ENGINE = MYISAM,
CHARACTER SET utf8mb4,
CHECKSUM = 0,
COLLATE utf8mb4_vietnamese_ci;

--
-- Create table `lands`
--
CREATE TABLE lands (
  land_id int(11) NOT NULL AUTO_INCREMENT,
  user_id varchar(255) DEFAULT NULL,
  post_id int(11) DEFAULT NULL,
  create_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  facade_area varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  catalog varchar(255) DEFAULT NULL,
  image_url varchar(255) DEFAULT NULL,
  price int(11) NOT NULL,
  title varchar(255) DEFAULT NULL,
  PRIMARY KEY (land_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci;

-- 
-- Dumping data for table lands1
--
-- Table lands.lands1 does not contain any data (it is empty)

-- 
-- Dumping data for table lands
--
-- Table lands.lands does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;