--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.124.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04/12/2019 10:16:30 SA
-- Server version: 8.0.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS room;

CREATE DATABASE room
CHARACTER SET utf8mb4
COLLATE utf8mb4_vietnamese_ci;

--
-- Set default database
--
USE room;

--
-- Create table `rooms`
--
CREATE TABLE rooms (
  room_id int(11) NOT NULL AUTO_INCREMENT,
  house_id int(11) DEFAULT NULL,
  room_name varchar(255) DEFAULT NULL,
  day_price int(11) DEFAULT NULL,
  month_price int(11) DEFAULT NULL,
  status varchar(255) DEFAULT NULL,
  PRIMARY KEY (room_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_vietnamese_ci;

-- 
-- Dumping data for table rooms
--
-- Table room.rooms does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;